# Generated by Django 5.0.3 on 2024-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='used_in',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
