# Generated by Django 5.0.3 on 2024-03-13 07:28

import datetime
import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_expense_used_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_in', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=50, verbose_name=polls.models.category)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.DeleteModel(
            name='expense',
        ),
    ]
