# Generated by Django 5.0.3 on 2024-03-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_account_delete_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
        ),
    ]
